declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_DEBUG_CONTROLS?: string;
    NEXT_PUBLIC_FETCH_INTERVAL_SECONDS?: string;
    NEXT_PUBLIC_TRANSITION_DURATION_MS?: string;
    NEXT_PUBLIC_SLIDE_INTERVAL_SECONDS?: string;
    NEXT_PUBLIC_FETCH_INTERVAL_SECONDS?: string;
  }
}
